create-secret-manager-secret:
  enabled: true
  secrets:
    - secretName: test-sa
      vals:
        - kubeSecretKey: datareposerviceaccount
          path: secret/dsde/datarepo/integration/sa-key-b64
          encoding: base64
          vaultKey: sa
    - secretName: test-azure
      vals:
        - kubeSecretKey: applicationsecret
          path: secret/dsde/datarepo/integration/helm-azure-integration
          vaultKey: applicationsecret
        - kubeSecretKey: synapse-us-east-sql-admin-user
          path: dsde/datarepo/integration/helm-azure-integration
          vaultKey: synapse-us-east-sql-admin-user
        - kubeSecretKey: synapse-us-east-sql-admin-password
          path: dsde/datarepo/integration/helm-azure-integration
          vaultKey: synapse-us-east-sql-admin-password
    - secretName: test-rbs-sa
      vals:
        - kubeSecretKey: rbsserviceaccount
          path: secret/dsde/terra/kernel/integration/tools/buffer/client-sa
          encoding: base64
          vaultKey: key

gcloud-sqlproxy:
  enabled: false

datarepo-api:
  enabled: true
  fullnameOverride: test-datarepo-api
  image:
    tag: 1.143.0
  env:
    GOOGLE_PROJECTID: broad-jade-integration
    GOOGLE_SINGLEDATAPROJECTID: broad-jade-integration-data
    GOOGLE_ALLOWREUSEEXISTINGBUCKETS: true
    GOOGLE_ALLOWREUSEEXISTINGPROJECTS: true
    DB_DATAREPO_USERNAME: drmanager
    SPRING_PROFILES_ACTIVE: google,cloudsql,temp
    DB_STAIRWAY_USERNAME: drmanager
    DB_STAIRWAY_URI: jdbc:postgresql://test-postgresql.integration-temp:5432/stairway
    DB_DATAREPO_URI: jdbc:postgresql://test-postgresql.integration-temp:5432/datarepo
    DATAREPO_DNSNAME: jade-temp.datarepo-integration.broadinstitute.org
    IT_JADE_API_URL: https://jade-temp.datarepo-integration.broadinstitute.org
    AZURE_CREDENTIALS_APPLICATIONID: 22cb243c-f1a5-43d8-8f12-6566bcce6542
    AZURE_CREDENTIALS_HOMETENANTID: fad90753-2022-4456-9b0a-c7e5b934e408
    RBS_ENABLED: true
    RBS_POOL_ID: datarepo_v1
    RBS_INSTANCE_URL: https://buffer.tools.integ.envs.broadinstitute.org
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingSecretDB: "test-postgresql"
  existingDatarepoDbSecretKey: "postgresql-password"
  existingStairwayDbSecretKey: "postgresql-password"
  existingSecretSA: "test-sa"
  existingServiceAccountSecretKey: "datareposerviceaccount"
  existingSecretAzure: "test-azure"
  existingApplicationSecretSecretKey: "applicationsecret"
  existingSynapseUserSecretKey: "synapse-us-east-sql-admin-user"
  existingSynapsePasswordSecretKey: "synapse-us-east-sql-admin-password"
  existingSecretRBS: "test-rbs-sa"
  existingRBSSecretKey: "rbsserviceaccount"

datarepo-ui:
  enabled: true
  fullnameOverride: test-datarepo-ui
  image:
    tag: 0.73.0
  proxyPass:
    status: http://test-datarepo-api.integration-temp:8080/status
    shutdown: http://test-datarepo-api.integration-temp:8080/shutdown
    swagger: http://test-datarepo-api.integration-temp:8080/swagger-ui.html
    api: http://test-datarepo-api.integration-temp:8080
  serviceAccount:
    create: true
  rbac:
    create: true

oidc-proxy:
  enabled: true
  fullnameOverride: test-oidc-proxy
  env:
    PROXY_URL: http://test-datarepo-ui.integration-temp:8080/
    PROXY_URL2: http://test-datarepo-api.integration-temp:8080/api
    PROXY_URL3: http://test-datarepo-api.integration-temp:8080/register
    LOG_LEVEL: debug
    SERVER_NAME: jade.datarepo-integration.broadinstitute.org
    REMOTE_USER_CLAIM: sub
    ENABLE_STACKDRIVER: yes
    FILTER2: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript application/x-javascript
  ingress:
    enabled: false
  service:
    type: ClusterIP
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true

de-elasticsearch:
  enabled: true
  fullnameOverride: test-de-elasticsearch
