appVersion: "1.16"
description: Google Cloud SQL Proxy
engine: gotpl
home: https://cloud.google.com/sql/docs/postgres/sql-proxy
keywords:
- google
- cloud
- postgresql
- mysql
- sql
- sqlproxy
maintainers:
- email: monster@broadinstitute.org
  name: Monster
- email: jadeteam@broadinstitute.org
  name: Jade
name: gcloud-sqlproxy
sources:
- https://github.com/broadinstitute/datarepo-helm
version: 0.19.4
