{{- range .Values.esoSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .secretName }}
  labels: {{- include "datarepo.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  data:
    {{- range .vals}}
    - secretKey: api-key
      remoteRef:
        key: tcell-api-key
        property: tcell_api_key
    {{- end}}
{{- end -}}
