{{- range .Values.secrets }}
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .secretName }}
  {{- if .nameSpace }}
  namespace: {{ .nameSpace }}
  {{- end }}
spec:
  name: {{ .secretName }}
  keysMap:
    {{- range .vals}}
    {{ .kubeSecretKey }}:
      path: {{ .path }}
      {{- if .encoding }}
      encoding: {{ .encoding }}
      {{- end }}
      key: {{ .vaultKey }}
    {{- end }}
{{- end -}}

{{- range .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .secretName }}
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  refreshInterval: {{ .refreshInterval | quote }}
  data:
    {{- range .data}}
    - secretKey: {{ .secretKey}}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
        {{- if .decodingStrategy }}
        decodingStrategy: {{ .decodingStrategy }}
        {{- end }}
    {{- end}}
{{- end -}}
