{{- range .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .secretName }}
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  refreshInterval: {{ .refreshInterval | quote }}
  data:
    {{- range .data}}
    - secretKey: {{ .secretKey}}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
        {{- if .remoteRef.decodingStrategy }}
        decodingStrategy: {{ .remoteRef.decodingStrategy }}
        {{- end }}
    {{- end}}
{{- end -}}
