{{- range .Values.secrets }}
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .secretName }}
spec:
  name: {{ .secretName }}
  keysMap:
    {{- range .vals}}
    {{ .kubeSecretKey }}:
      path: {{ .path }}
      {{- if .encoding }}
      encoding: .encoding
      {{- end }}
      key: {{ .vaultKey }}
    {{- end }}
{{- end -}}
