---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: secretdefinition-sample
spec:
  name: secrets
  keysMap:
{{- range .Values.secrets }}
    "{{ .name }}":
      path: "{{ .path }}"
      {{- if .encoding }}
      encoding: .encoding
      {{- end }}
      key: "{{ .key }}"
{{- end -}}
