---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ include "create-secret-manager-secret.fullname" . }}
spec:
  name: {{ .Values.secretName }}
  keysMap:
{{- range .Values.secrets }}
    {{ .kubeSecretKey }}:
      path: {{ .path }}
      {{- if .encoding }}
      encoding: .encoding
      {{- end }}
      key: {{ .vaultKey }}
{{- end -}}
