---
# setup temp postgres
# helm upgrade test bitnami/postgresql -f .github/postgres-values.yaml --install --namespace integration-temp --create-namespace
global:
  postgresql:
    postgresqlUsername: postgres
    postgresqlPassword: postgres
serviceAccount:
  enabled: true
psp:
  create: true
rbac:
  create: true
persistence:
  enabled: true
initdbUser: postgres
initdbPassword: postgres
initdbScripts:
  init.sql: |
    CREATE USER drmanager WITH PASSWORD 'postgres';
    CREATE DATABASE stairway WITH OWNER drmanager;
    CREATE DATABASE datarepo WITH OWNER drmanager;
    ALTER USER drmanager WITH SUPERUSER;
    \c datarepo;
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
