{{- $hasCredentials := include "travis-ips-auth.hasCredentials" . -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "travis-ips-auth.fullname" . }}
  labels:
    {{- include "travis-ips-auth.labels" . | nindent 4 }}
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "travis-ips-auth.serviceAccountName" . }}
          containers:
          - name: {{ .Chart.Name }}
            image: google/cloud-sdk:slim
            command: ["/bin/sh", "-c", "gcloud auth activate-service-account {{ .Values.GcpSaEmail }} \
            --key-file=/secrets/creds.json && apt-get -qq install jq -y > /dev/null && \
            CURRENT=$(gcloud container clusters describe integration-us-central1-k8s --zone us-central1-a --format json | \
              jq -r '[.masterAuthorizedNetworksConfig.cidrBlocks[] | .cidrBlock]') &&  \
            TRAVIS_IPS=$(curl -s https://dnsjson.com/nat.gce-us-central1.travisci.net/A.json | \
                jq '.results.records | map(.+\"/32\")') && \
            NEW_IPS=$(printf '%s\n' $CURRENT $TRAVIS_IPS | jq -s -r \'add | unique | join(\",\")') && \
            gcloud container clusters update integration-us-central1-k8s --zone us-central1-a --project broad-jade-integration \
                --enable-master-authorized-networks \
                --master-authorized-networks $NEW_IPS"]
            volumeMounts:
              {{- if $hasCredentials }}
              - name: {{ include "travis-ips-auth.fullname" . }}
                mountPath: /secrets/
                readOnly: true
              {{- end }}
          volumes:
            {{- if $hasCredentials }}
            - name: {{ include "travis-ips-auth.fullname" . }}
              secret:
                secretName: {{ include "travis-ips-auth.secretNameSA" . }}
                items:
                  - key: {{ include "travis-ips-auth.secretKeyServiceAccount" . }}
                    path: creds.json
            {{- end }}
          restartPolicy: Never
      backoffLimit: 4
