apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sqlbackup.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sqlbackup.labels" . | nindent 4 }}
data:
  {{- if .Values.backupCronJob.enabled }}
  backup: |-
    {{- include "backup" . | indent 4 }}
  {{- end }}
  {{- if .Values.cleanupCronJob.enabled }}
  cleanup: |-
    {{- include "cleanup" . | indent 4 }}
  {{- end }}
