---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: {{ include "backend-config.fullname" . }}
  labels:
    {{- include "backend-config.labels" . | nindent 4 }}
spec:
  securityPolicy:
    name: {{ .Values.securityPolicy }}
