---
fullnameOverride: test-datarepo-ui
image:
  tag: 0.0.168
proxyPass:
  status: http://test-datarepo-api.integration-temp:8080/status
  shutdown: http://test-datarepo-api.integration-temp:8080/shutdown
  swagger: http://test-datarepo-api.integration-temp:8080/swagger-ui.html
  api: http://test-datarepo-api.integration-temp:8080
serviceAccount:
  create: true
rbac:
  create: true
