{{- $hasCredentials := include "datarepo-api.hasCredentials" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datarepo-api.fullname" . }}
  labels:
    {{- include "datarepo-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ include "datarepo-api.fullname" . }}
  template:
    metadata:
      labels:
{{- include "datarepo-api.labels" . | nindent 8 }}
        app: {{ include "datarepo-api.fullname" . }}
        component: {{ include "datarepo-api.fullname" . }}
##  dynamically populates environment annotations
      annotations:
        {{ if .Values.secretsgeneric.datarepoPassword -}}
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
{{ toYaml .Values.podAnnotations | indent 8 }}
    spec:
      serviceAccountName: {{ include "datarepo-api.serviceAccountName" . }}
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        runAsNonRoot: true
      volumes:
        {{- if $hasCredentials }}
        - name: google-cloud-key
          secret:
            secretName: {{ include "datarepo-api.secretNameSA" . }}
            items:
              - key: {{ include "datarepo-api.secretKeyServiceAccount" . }}
                path: sa-key.json
        {{- end }}
      terminationGracePeriodSeconds: {{ .Values.shutdownTimeoutSeconds }}
      containers:
      - name: {{ include "datarepo-api.fullname" . }}
        image: {{ include "datarepo-api.image" . }}
        readinessProbe:
          httpGet:
            path: /status
            port: {{ .Values.image.port }}
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /status
            port: {{ .Values.image.port }}
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        lifecycle:
          preStop:
            httpGet:
              port: 8080
              path: /shutdown
        volumeMounts:
        {{ if $hasCredentials -}}
        - name: google-cloud-key
          mountPath: /var/secrets/google/
        {{ end -}}
        ports:
        - containerPort: {{ .Values.image.port }}
        - containerPort: 5005
##  dynamically populates environment variables
        env:
        {{- if .Values.env }}
        {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{ if $hasCredentials -}}
        - name: DB_DATAREPO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "datarepo-api.secretNameDB" . }}
              key: {{ include "datarepo-api.secretKeyDatarepoDb" . }}
        - name: DB_STAIRWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "datarepo-api.secretNameDB" . }}
              key: {{ include "datarepo-api.secretKeyStairwayDb" . }}
        {{ end -}}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/sa-key.json
# Supply the pod name: used to identify Stairway instances
        - name: DATAREPO_PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
# Share the timeout value between Kubernetes and Datarepo
        - name: DATAREPO_SHUTDOWNTIMEOUTSECONDS
          value: "{{ .Values.shutdownTimeoutSeconds }}"
# Tell Datarepo is it running in kubernetes
        - name: DATAREPO_INKUBERNETES
          value: "true"
{{- if .Values.resources }}
        resources:
{{- toYaml .Values.resources | nindent 10 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{- toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{- toYaml .Values.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
