{{- $hasCredentials := include "datarepo-api.hasCredentials" . -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ include "datarepo-api.fullname" . }}
  labels:
    {{- include "datarepo-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ include "datarepo-api.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "datarepo-api.fullname" . }}
        component: {{ include "datarepo-api.fullname" . }}
    spec:
      serviceAccountName: {{ include "datarepo-api.serviceAccountName" . }}
      volumes:
        {{- if $hasCredentials }}
        - name: google-cloud-key
          secret:
            secretName: {{ include "datarepo-api.secretNameSA" . }}
            items:
              - key: {{ include "datarepo-api.secretKeyServiceAccount" . }}
                path: sa-key.json
        {{- end }}
      containers:
      - name: {{ include "datarepo-api.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        readinessProbe:
          httpGet:
            path: /status
            port: {{ .Values.image.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /status
            port: {{ .Values.image.port }}
          initialDelaySeconds: 25
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        {{ if $hasCredentials -}}
        - name: google-cloud-key
          mountPath: /var/secrets/google/
        {{ end -}}
        ports:
        - containerPort: {{ .Values.image.port }}
        - containerPort: 5005
        env:
        {{- if .Values.env.serverContextpath }}
        - name: SERVER_CONTEXTPATH
          value: {{ .Values.env.serverContextpath }}
        {{- end }}
        {{- if .Values.env.serverPort }}
        - name: SERVER_PORT
          value: {{ .Values.env.serverPort }}
        {{- end }}
        {{- if .Values.env.springDatasourceTomcatTestOnBorrow }}
        - name: SPRING_DATASOURCE_TOMCAT_TEST-ON-BORROW
          value: {{ .Values.env.springDatasourceTomcatTestOnBorrow }}
        {{- end }}
        {{- if .Values.env.springDatasourceTomcatValidationQuery }}
        - name: SPRING_DATASOURCE_TOMCAT_VALIDATION-QUERY
          value: {{ .Values.env.springDatasourceTomcatValidationQuery }}
        {{- end }}
        {{- if .Values.env.springJacksonSerializationWriteDatesAsTimestamps }}
        - name: SPRING_JACKSON_SERIALIZATION_WRITE_DATES_AS_TIMESTAMPS
          value: {{ .Values.env.springJacksonSerializationWriteDatesAsTimestamps }}
        {{- end }}
        {{- if .Values.env.springLiquibaseEnabled }}
        - name: SPRING_LIQUIBASE_ENABLED
          value: {{ .Values.env.springLiquibaseEnabled }}
        {{- end }}
        {{- if .Values.env.springProfilesActive }}
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.env.springProfilesActive }}
        {{- end }}
        {{- if .Values.env.springfoxDocumentationSwaggerV2Path }}
        - name: SPRINGFOX_DOCUMENTATION_SWAGGER_V2_PATH
          value: {{ .Values.env.springfoxDocumentationSwaggerV2Path }}
        {{- end }}
        {{- if .Values.env.dbMigrateDropallonstart }}
        - name: DB_MIGRATE_DROPALLONSTART
          value: {{ .Values.env.dbMigrateDropallonstart }}
        {{- end }}
        {{- if .Values.env.dbMigrateUpdateallonstart }}
        - name: DB_MIGRATE_UPDATEALLONSTART
          value: {{ .Values.env.dbMigrateUpdateallonstart }}
        {{- end }}
        {{- if .Values.env.dbDatarepoUri }}
        - name: DB_DATAREPO_URI
          value: {{ .Values.env.dbDatarepoUri }}
        {{- end }}
        {{- if .Values.env.dbDatarepoUsername }}
        - name: DB_DATAREPO_USERNAME
          value: {{ .Values.env.dbDatarepoUsername }}
        {{- end }}
        {{- if .Values.env.dbDatarepoPassword }}
        - name: DB_DATAREPO_PASSWORD
          value: {{ .Values.env.dbDatarepoPassword }}
        {{- end }}
        {{- if .Values.env.dbDatarepoChangesetfile }}
        - name: DB_DATAREPO_CHANGESETFILE
          value: {{ .Values.env.dbDatarepoChangesetfile }}
        {{- end }}
        {{- if .Values.env.dbStairwayUri }}
        - name: DB_STAIRWAY_URI
          value: {{ .Values.env.dbStairwayUri }}
        {{- end }}
        {{- if .Values.env.dbStairwayUsername }}
        - name: DB_STAIRWAY_USERNAME
          value: {{ .Values.env.dbStairwayUsername }}
        {{- end }}
        {{- if .Values.env.dbStairwayPassword }}
        - name: DB_STAIRWAY_PASSWORD
          value: {{ .Values.env.dbStairwayPassword }}
        {{- end }}
        {{- if .Values.env.dbStairwayChangesetfile }}
        - name: DB_STAIRWAY_CHANGESETFILE
          value: {{ .Values.env.dbStairwayChangesetfile }}
        {{- end }}
        {{- if .Values.env.dbStairwayForceclean }}
        - name: DB_STAIRWAY_FORCECLEAN
          value: {{ .Values.env.dbStairwayForceclean }}
        {{- end }}
        {{- if .Values.env.oauthClientid }}
        - name: OAUTH_CLIENTID
          value: {{ .Values.env.oauthClientid }}
        {{- end }}
        {{- if .Values.env.oauthSchemename }}
        - name: OAUTH_SCHEMENAME
          value: {{ .Values.env.oauthSchemename }}
        {{- end }}
        {{- if .Values.env.oauthLoginendpoint }}
        - name: OAUTH_LOGINENDPOINT
          value: {{ .Values.env.oauthLoginendpoint }}
        {{- end }}
        {{- if .Values.env.oauthScopes }}
        - name: OAUTH_SCOPES
          value: {{ .Values.env.oauthScopes }}
        {{- end }}
        {{- if .Values.env.datarepoResourceid }}
        - name: DATAREPO_RESOURCEID
          value: {{ .Values.env.datarepoResourceid }}
        {{- end }}
        {{- if .Values.env.datarepoUseremail }}
        - name: DATAREPO_USEREMAIL
          value: {{ .Values.env.datarepoUseremail }}
        {{- end }}
        {{- if .Values.env.datarepoDnsname }}
        - name: DATAREPO_DNSNAME
          value: {{ .Values.env.datarepoDnsname }}
        {{- end }}
        {{- if .Values.env.datarepoUserid }}
        - name: DATAREPO_USERID
          value: {{ .Values.env.datarepoUserid }}
        {{- end }}
        {{- if .Values.env.datarepoMaxstairwaythreads }}
        - name: DATAREPO_MAXSTAIRWAYTHREADS
          value: {{ .Values.env.datarepoMaxstairwaythreads }}
        {{- end }}
        {{- if .Values.env.datarepoGcsBucket }}
        - name: DATAREPO_GCS_BUCKET
          value: {{ .Values.env.datarepoGcsBucket }}
        {{- end }}
        {{- if .Values.env.datarepoGcsRegion }}
        - name: DATAREPO_GCS_REGION
          value: {{ .Values.env.datarepoGcsRegion }}
        {{- end }}
        {{- if .Values.env.datarepoGcsConnecttimeoutseconds }}
        - name: DATAREPO_GCS_CONNECTTIMEOUTSECONDS
          value: {{ .Values.env.datarepoGcsConnecttimeoutseconds }}
        {{- end }}
        {{- if .Values.env.datarepoGcsReadtimeoutseconds }}
        - name: DATAREPO_GCS_READTIMEOUTSECONDS
          value: {{ .Values.env.datarepoGcsReadtimeoutseconds }}
        {{- end }}
        {{- if .Values.env.samBasepath }}
        - name: SAM_BASEPATH
          value: {{ .Values.env.samBasepath }}
        {{- end }}
        {{- if .Values.env.samStewardsgroupemail }}
        - name: SAM_STEWARDSGROUPEMAIL
          value: {{ .Values.env.samStewardsgroupemail }}
        {{- end }}
        {{- if .Values.env.samRetryinitialwaitseconds }}
        - name: SAM_RETRYINITIALWAITSECONDS
          value: {{ .Values.env.samRetryinitialwaitseconds }}
        {{- end }}
        {{- if .Values.env.samRetrymaximumwaitseconds }}
        - name: SAM_RETRYMAXIMUMWAITSECONDS
          value: {{ .Values.env.samRetrymaximumwaitseconds }}
        {{- end }}
        {{- if .Values.env.samOperationtimeoutseconds }}
        - name: SAM_OPERATIONTIMEOUTSECONDS
          value: {{ .Values.env.samOperationtimeoutseconds }}
        {{- end }}
        {{- if .Values.env.googleProjectid }}
        - name: GOOGLE_PROJECTID
          value: {{ .Values.env.googleProjectid }}
        {{- end }}
        {{- if .Values.env.googleApplicationname }}
        - name: GOOGLE_APPLICATIONNAME
          value: {{ .Values.env.googleApplicationname }}
        {{- end }}
        {{- if .Values.env.googleProjectcreatetimeoutseconds }}
        - name: GOOGLE_PROJECTCREATETIMEOUTSECONDS
          value: {{ .Values.env.googleProjectcreatetimeoutseconds }}
        {{- end }}
        {{- if .Values.env.googleCorebillingaccount }}
        - name: GOOGLE_COREBILLINGACCOUNT
          value: {{ .Values.env.googleCorebillingaccount }}
        {{- end }}
        {{- if .Values.env.googleParentresourcetype }}
        - name: GOOGLE_PARENTRESOURCETYPE
          value: {{ .Values.env.googleParentresourcetype }}
        {{- end }}
        {{- if .Values.env.googleParentresourceid }}
        - name: GOOGLE_PARENTRESOURCEID
          value: {{ .Values.env.googleParentresourceid }}
        {{- end }}
        {{ if $hasCredentials -}}
        - name: DB_DATAREPO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "datarepo-api.secretNameDB" . }}
              key: {{ include "datarepo-api.secretKeyDatarepoDb" . }}
        - name: DB_STAIRWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "datarepo-api.secretNameDB" . }}
              key: {{ include "datarepo-api.secretKeyStairwayDb" . }}
        {{ end -}}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/sa-key.json
