{{- if .Values.sherlock.enabled }}
# The purpose of this file is to create a k8s Job that reports
# deploys of new application builds to sherlock (Terra's environment tracking service)
# after each argo sync
{{ template "sherlock-reporter.secret" . }}
---
{{ template "sherlock-reporter.job" . }}
{{- end -}}
