{{- if .Values.rbac.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "datarepo-api.fullname" . }}-use-pod-security-policy-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ["use"]
  resourceNames:
    - {{ include "datarepo-api.fullname" . }}-pod-running-policy
{{- end }}
