---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ template "frontend-config.fullname" . }}
  labels:
    {{- include "frontend-config.labels" . | nindent 4 }}
spec:
  sslPolicy: {{ .Values.sslPolicy }}
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT