apiVersion: v2
description: Chart for creating gcp managed certs
name: gcp-managed-cert
type: application
version: 0.1.3
appVersion: 0.1.3

keywords:
- google
- cloud
- datarepo
- broadinstitute

maintainers:
- email: smark@broadinstitute.org
  name: smark

sources:
- https://github.com/broadinstitute/datarepo-helm/tree/master/charts

home: https://broadinstitute.github.io/datarepo-helm/
