secrets:

# - secretName:     ## name of kubeSecret
#  nameSpace: ""
#  vals:
#  - kubeSecretKey: ""    ## name of kubeSecretKey
#    encoding: ""     ## if secret is base64 already use this flagg
#    vaultKey:  ""   ## vault key name
#  - kubeSecretKey:  ## name of kubeSecretKey
#    path:  ## vault path
#    vaultKey:  ## vault key name

externalSecrets:
  secrets: []
  refreshInterval: "5m"

# - secretName:               ## name of kubeSecret
#   data:
#     - secretKey:            ## name of kubeSecretKey
#       remoteRef:
#         key:                ## key name
#         property:           ## description of secret
#         decodingStrategy:   ## how to decode secret
