apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cron-job.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cron-job.labels" . | nindent 4 }}
data:
  script.sh: |-
    {{ .Values.script | nindent 4 }}
