{{- $hasCredentials := include "cron-job.hasCredentials" . -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cron-job.fullname" . }}
  labels:
    {{- include "cron-job.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "cron-job.serviceAccountName" . }}
          containers:
          - name: {{ include "cron-job.fullname" . }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
            command: ["/bin/sh", "-c", "/opt/script/script.sh"]
          {{ if $hasCredentials -}}
          env:
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "cron-job.secretName" . }}
                key: {{ include "cron-job.secretKey" . }}
          {{ end -}}
            volumeMounts:
              {{- if $hasCredentials }}
              - name: {{ include "cron-job.fullname" . }}
                mountPath: /secrets/
                readOnly: true
              {{- end }}
              - name: script
                mountPath: /opt/script
                readOnly: false
          volumes:
            {{- if $hasCredentials }}
            - name: {{ include "cron-job.fullname" . }}
              secret:
                secretName: {{ include "cron-job.secretName" . }}
                items:
                  - key: {{ include "cron-job.secretKey" . }}
                    path: creds.json
            {{- end }}
            - name: script
              configMap:
                name: {{ template "cron-job.fullname" . }}
                defaultMode: 0755
          restartPolicy: Never
      backoffLimit: 4
