{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cron-job.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cron-job.labels" . | nindent 4 }}
data:
  credential-file-json: {{ .Values.secretsgeneric.newSecret | b64enc | quote }}
{{- end }}
