apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "datarepo-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datarepo-ui.labels" . | nindent 4 }}
data:
  nginxconf: |-
    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      server { # simple reverse-proxy
        listen       80;

        # pass the status check through
        location /status {
            proxy_pass {{ .Values.proxyPass.status }};
        }

        # get swagger working
        location /swagger-ui.html {
            proxy_pass {{ .Values.proxyPass.swagger }};
        }

        location ~ (configuration|ga4gh|webjars|api-docs|swagger-resources) {
            proxy_pass {{ .Values.proxyPass.api }};
        }

        # serve static files
        location / {
          root /usr/share/nginx/html;
          try_files $uri /index.html =404;
        }
      }
    }
