{{- if .Values.rbac.create }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: "{{ include "datarepo-ui.fullname" . }}-pod-running-policy"
  namespace: {{ .Release.Namespace }}
  labels:
    name: podsecuritypolicy
    {{- include "datarepo-ui.labels" . | nindent 4 }}
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
{{- end }}
