{{- if .Values.rbac.pspEnabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: "{{ include "datarepo-ui.fullname" . }}-ui-pod-running-policy"
  namespace: {{ .Release.Namespace }}
  labels:
    name: podsecuritypolicy
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
{{- end }}
