apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datarepo-ui.fullname" . }}
  labels:
    {{- include "datarepo-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ include "datarepo-ui.fullname" . }}
  template:
    metadata:
      labels:
        component: {{ include "datarepo-ui.fullname" . }}
    spec:
      serviceAccountName: {{ include "datarepo-ui.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "datarepo-ui.image" . }}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 35
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
          - name: nginxconf
            mountPath: /etc/nginx/
      volumes:
        - name: nginxconf
          configMap:
            name: {{ include "datarepo-ui.fullname" . }}
            items:
              - key: nginxconf
                path: nginx.conf
