apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datarepo-ui.fullname" . }}
  labels:
    {{- include "datarepo-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ if (($.Values).global).replicasOffline | default false -}}
      0
    {{- else -}}
      {{ .Values.replicaCount }}
    {{- end }}
  selector:
    matchLabels:
      component: {{ include "datarepo-ui.fullname" . }}
  template:
    metadata:
      labels:
{{- include "datarepo-ui.labels" . | nindent 8 }}
        component: {{ include "datarepo-ui.fullname" . }}
##  dynamically populates environment annotations
      annotations:
      {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
        checksum/configmap: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "datarepo-ui.serviceAccountName" . }}
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        runAsNonRoot: true
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "datarepo-ui.image" . }}
        ports:
        - containerPort: {{ .Values.nginxport }}
##  dynamically populates environment variables
        env:
        {{- if .Values.env }}
        {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "[ -f /tmp/nginx.pid ] && ps -A | grep nginx"
          initialDelaySeconds: 35
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "[ -f /tmp/nginx.pid ] && ps -A | grep nginx"
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
          - name: nginxconf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: nginxconf
          configMap:
            name: {{ include "datarepo-ui.fullname" . }}
            items:
              - key: nginxconf
                path: nginx.conf
{{- if .Values.resources }}
        resources:
{{- toYaml .Values.resources | nindent 10 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{- toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{- toYaml .Values.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
