# Default values for oidc-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

## Versions can be found here:
## https://github.com/broadinstitute/openidc-terra-proxy/tags
image:
  repository: us.gcr.io/broad-dsp-gcr-public/openidc-terra-proxy
  version: v0.1.12
  pullPolicy: IfNotPresent

## Extra environment variables that will be pass onto deployment pods
env: {}

## TCELL
tcell:
  enabled: false
  ## Note: the secret must contain an app-id value and an api-key value
  tcellSecret: ""
  host_identifier: ""

## Pod annotations
podAnnotations: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

## Node selectors and tolerations for server scheduling to nodes with taints
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
##
nodeSelector: {}
tolerations: []
affinity: {}

resources: {}
#  limits:
#    cpu: 50m
#    memory: 64Mi
#  requests:
#    cpu: 10m
#    memory: 32Mi

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

rbac:
  # Specifies whether a psp should be created
  create: false

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  sslPolicy:
  annotations: {}
  domainName: ""
  timeoutSec: 600
  ingressAllowHttp: false
  paths:
    - /*
  hosts: []
      # - datarepo.example.com
  tls:
    []
    # - secretName: datarepo-example-tls
    #   hosts:
    #     - datarepo.example.com
  b2cMetadataEndpoints:
    - https://terradevb2c.b2clogin.com/terradevb2c.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration
    - https://terradevb2c.b2clogin.com/terradevb2c.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN_TDR/v2.0/.well-known/openid-configuration
    - https://tdrb2ctest.b2clogin.com/tdrb2ctest.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN_TDR/v2.0/.well-known/openid-configuration

# 
# New fields by DevOps
#

# use cert-manager to rotate certs
cert-manager:
  enabled: false

# use external-dns to manage dns provisioning
externalDNS:
  enabled: false
