create-secret-manager-secret:
  enabled: false

backend-config:
  enabled: false

grafana-gcp-managed-cert:
  enabled: false

prometheus-gcp-managed-cert:
  enabled: false

prometheus-operator:
  enabled: false
