apiVersion: v2
name: datarepo-ui
description: A Helm chart to deploy datarepo ui server for Kubernetes
type: application
version: 0.0.92
appVersion: 0.73.0
keywords:
  - google
  - cloud
  - datarepo
  - broadinstitute
maintainers:
  - email: smark@broadinstitute.org
    name: smark
sources:
  - https://github.com/broadinstitute/datarepo-helm/tree/master/charts
home: https://broadinstitute.github.io/datarepo-helm/
