{{- if .Values.rbac.create -}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "secrets-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: secrets-manager
    {{- include "secrets-manager.labels" . | nindent 4 }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ["use"]
  resourceNames:
    - "{{ include "secrets-manager.fullname" . }}-pod-running-policy"
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "get"
  - "list"
  - "watch"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "secrets-manager.fullname" . }}
  labels:
    app: secrets-manager
    {{- include "secrets-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "update"
  - "delete"
  - "create"
{{- end }}
