{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secrets-manager.serviceAccountName" . }}
  labels:
    app: secrets-manager
    {{ include "secrets-manager.labels" . | nindent 4 }}
{{- end -}}
