apiVersion: v2
name: datarepo
description: A Helm chart to deploy an entire datarepo
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version

version: 0.1.423
appVersion: 0.1.423
keywords:
- google
- cloud
- datarepo
- broadinstitute
maintainers:
- email: smark@broadinstitute.org
  name: smark
sources:
- https://github.com/broadinstitute/datarepo-helm/tree/master/charts
# dependencies
dependencies:
- name: datarepo-api
  version: 0.0.329
  repository: https://broadinstitute.github.io/datarepo-helm/
  condition: datarepo-api.enabled
- name: oidc-proxy
  version: 0.0.31
  repository: https://broadinstitute.github.io/datarepo-helm/
  condition: oidc-proxy.enabled
- name: datarepo-ui
  version: 0.0.143
  repository: https://broadinstitute.github.io/datarepo-helm/
  condition: datarepo-ui.enabled
- name: gcloud-sqlproxy
  version: 0.19.7
  repository: https://broadinstitute.github.io/datarepo-helm/
  condition: gcloud-sqlproxy.enabled
- name: create-secret-manager-secret
  version: 0.0.6
  repository: https://broadinstitute.github.io/datarepo-helm/
  condition: create-secret-manager-secret.enabled
- name: de-elasticsearch
  version: 0.1.4
  repository: https://broadinstitute.github.io/datarepo-helm/
  condition: de-elasticsearch.enabled
