apiVersion: v2
name: datarepo
description: A Helm chart to deploy an entire datarepo

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.16.0
# dependencies
dependencies:
- name: datarepo-api
  version: ^0.1.1
  repository: https://broadinstitute.github.io/broad-dsp-helm/index.yaml
  condition: datarepo-api.enabled
- name: oidc-proxy
  version: ^0.1.1
  repository: https://broadinstitute.github.io/broad-dsp-helm/charts/
  condition: oidc-proxy.enabled
- name: datarepo-ui
  version: ^0.1.1
  repository: https://broadinstitute.github.io/broad-dsp-helm/charts/
  condition: datarepo-ui.enabled
- name: gcloud-sqlproxy
  version: ^0.6.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: gcloud-sqlproxy.enabled
- name: postgresql
  version: ^7.7.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
