{{- if .Values.rbac.create -}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "install-secrets-manager.fullname" . }}-role"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    {{- include "install-secrets-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ include "install-secrets-manager.fullname" . }}-clusterrole"
  labels:
    app: {{ .Chart.Name }}
    {{- include "install-secrets-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - secrets-manager.tuenti.io
  resources:
  - secretdefinitions
  verbs:
  - list
  - watch
  - get
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
  - delete
  - create
{{- end }}
