apiVersion: v2
name: de-elasticsearch
description: A Helm chart for elastic search in data explorer
type: application
version: 0.1.0
dependencies:
  - name: elasticsearch
    version: 7.10.2
    repository: https://helm.elastic.co
