apiVersion: v2
name: datarepomonitoring
description: A Helm chart to deploy an entire datarepomonitoring stack
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version
version: 0.0.3
appVersion: 0.0.3
keywords:
- google
- cloud
- datarepo
- broadinstitute
maintainers:
- email: smark@broadinstitute.org
  name: smark
sources:
- https://github.com/broadinstitute/datarepo-helm/tree/master/charts
# dependencies
dependencies:
- name: create-secret-manager-secret
  version: 0.0.7
  repository: https://broadinstitute.github.io/datarepo-helm/
  condition: create-secret-manager-secret.enabled
- name: backend-config
  version: 0.1.0
  repository: https://broadinstitute.github.io/datarepo-helm/
  condition: backend-config.enabled
- name: frontend-config
  version: 0.1.0
  repository: https://broadinstitute.github.io/datarepo-helm/
  condition: frontend-config.enabled
- name: gcp-managed-cert
  alias: grafana-gcp-managed-cert
  version: 0.1.3
  repository: https://broadinstitute.github.io/datarepo-helm/
  condition: grafana-gcp-managed-cert.enabled
- name: gcp-managed-cert
  alias: prometheus-gcp-managed-cert
  version: 0.1.3
  repository: https://broadinstitute.github.io/datarepo-helm/
  condition: prometheus-gcp-managed-cert.enabled
- name: kube-prometheus-stack
  version: 9.4.5
  repository: https://prometheus-community.github.io/helm-charts/
  condition: kube-prometheus-stack.enabled
