apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oidc-proxy.fullname" . }}
  labels:
    {{- include "oidc-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ include "oidc-proxy.fullname" . }}
  template:
    metadata:
      labels:
{{- include "oidc-proxy.labels" . | nindent 8 }}
        app: {{ include "oidc-proxy.fullname" . }}
        component: {{ include "oidc-proxy.fullname" . }}
##  dynamically populates environment annotations
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    spec:
      serviceAccountName: {{ include "oidc-proxy.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        # Based on the latest security review this is the recommended version of the proxy to use.
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 35
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
##  dynamically populates environment variables
        env:
        {{- if .Values.env }}
        {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        volumeMounts:
          {{- if or .Values.tcell.tcellSecret .Values.tcell.tcellSecretKey }}
          - mountPath: /etc/apache2/tcell_agent.config
            name: tcell
            subPath: tcell_agent.config
          {{- end }}
          - mountPath: /etc/apache2/sites-available/site.conf
            name: siteconf
            subPath: site.conf
      volumes:
        {{- if or .Values.tcell.tcellSecret .Values.tcell.tcellSecretKey }}
        - name: tcell
          secret:
            secretName: {{ .Values.tcel.tcellSecret }}
            items:
            - key: {{ .Values.tcel.tcellSecretKey }}
              path: tcell_agent.config
        {{- end }}
        - name: siteconf
          configMap:
            name: {{ template "oidc-proxy.fullname" . }}
            items:
              - key: siteconf
                path: site.conf

{{- if .Values.resources }}
        resources:
{{- toYaml .Values.resources | nindent 10 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{- toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{- toYaml .Values.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
