{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "oidc-proxy.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $paths := .Values.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.ingress.podAnnotations }}
  annotations:
    kubernetes.io/ingress.allow-http: {{ .Values.ingress.ingressAllowHttp | quote }}
{{ toYaml .Values.ingress.podAnnotations | indent 8 }}
{{- end }}
  name: {{ template "oidc-proxy.fullname" . }}
  labels:
    {{- include "datarepo-ui.labels" . | nindent 4 }}
spec:
  rules:
  {{- if .Values.ingress.hosts }}
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
  {{- range $p := $paths }}
          - path: {{ $p }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  {{- end -}}
  {{- end -}}
  {{- else }}
    - http:
        paths:
  {{- range $p := $paths }}
          - path: {{ $p }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  {{- end -}}
  {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}
