apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oidc-proxy.fullname" . }}
  labels:
    {{- include "oidc-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ include "oidc-proxy.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "oidc-proxy.fullname" . }}
        component: {{ include "oidc-proxy.fullname" . }}
    spec:
      serviceAccountName: {{ include "oidc-proxy.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        # Based on the latest security review this is the recommended version of the proxy to use.
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        ports:
        - containerPort: 80
        env:
          - name: PROXY_URL
            value: {{ .Values.env.proxyUrl | quote }}
          - name: PROXY_URL2
            value: {{ .Values.env.proxyUrl2 | quote }}
          - name: PROXY_URL3
            value: {{ .Values.env.proxyUrl3 | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.env.logLevel | quote }}
          - name: SERVER_NAME
            value: {{ .Values.env.serverName | quote }}
          - name: REMOTE_USER_CLAIM
            value: {{ .Values.env.remoteUserClaim | quote }}
          - name: ENABLE_STACKDRIVER
            value: {{ .Values.env.enableStackdriver | quote }}
          - name: FILTER2
            value: {{ .Values.env.filter2 | quote }}
        volumeMounts:
          - mountPath: /etc/apache2/sites-available/site.conf
            name: siteconf
            subPath: site.conf
      volumes:
        - name: siteconf
          configMap:
            name: {{ template "oidc-proxy.fullname" . }}
            items:
              - key: siteconf
                path: site.conf
