apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oidc-proxy.fullname" . }}
  labels:
    {{- include "oidc-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ include "oidc-proxy.fullname" . }}
  template:
    metadata:
      labels:
{{- include "oidc-proxy.labels" . | nindent 8 }}
        app: {{ include "oidc-proxy.fullname" . }}
        component: {{ include "oidc-proxy.fullname" . }}
##  dynamically populates environment annotations
      annotations:
      {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
        checksum/configmap: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "oidc-proxy.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        # Based on the latest security review this is the recommended version of the proxy to use.
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 80
          initialDelaySeconds: 35
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
##  dynamically populates environment variables
        env:
        {{- if .Values.env }}
        {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- if .Values.tcell.enabled }}
        - name: TCELL_AGENT_APP_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.tcell.tcellSecret }}
              key: app-id
        - name: TCELL_AGENT_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.tcell.tcellSecret }}
              key: api-key
        - name: ENABLE_TCELL
          value: 'yes'
        {{- end }}
        volumeMounts:
          {{- if .Values.tcell.enabled }}
          - mountPath: /etc/apache2/tcell_agent.config
            name: tcellconf
            subPath: tcell_agent.config
          {{- end }}
          - mountPath: /etc/apache2/sites-available/site.conf
            name: siteconf
            subPath: site.conf
          - mountPath: /etc/apache2/mods-enabled/oauth2.conf
            name: oauth2conf
            subPath: oauth2.conf
      volumes:
        - name: siteconf
          configMap:
            name: {{ template "oidc-proxy.fullname" . }}
            items:
              - key: siteconf
                path: site.conf
        - name: oauth2conf
          configMap:
            name: {{ template "oidc-proxy.fullname" . }}
            items:
              - key: oauth2conf
                path: oauth2.conf
        {{- if .Values.tcell.enabled }}
        - name: tcellconf
          configMap:
            name: {{ template "oidc-proxy.fullname" . }}
            items:
              - key: tcellconf
                path: tcell_agent.config
        {{- end }}

{{- if .Values.resources }}
        resources:
{{- toYaml .Values.resources | nindent 10 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{- toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{- toYaml .Values.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
