{{- if .Values.secret.enabled }}
kind: Secret
apiVersion: v1
metadata:
    name: {{ .Values.secret.name }}
type: Opaque
data:
    tls.key: {{ .Values.secret.tlsKey | b64enc | quote }}
    tls.crt:  {{ .Values.secret.tlsCert | b64enc | quote }}
{{- end }}
