{{- if not .Values.existingTlsSecret -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "oidc-proxy.fullname" . }}
  labels:
    {{- include "oidc-proxy.labels" . | nindent 4 }}
type: Opaque
data:
    tls.key: {{ .Values.secretsgeneric.tlsKey | b64enc }}
    tls.crt: {{ .Values.secretsgeneric.tlsCert | b64enc }}
{{- end }}
