{{- if .Values.secretsgeneric.enabled }}
kind: Secret
apiVersion: v1
metadata:
    name: {{ include "oidc-proxy.fullname" . }}
type: Opaque
data:
    tls.key: {{ .Values.secretsgeneric.tlsKey | b64enc | quote }}
    tls.crt:  {{ .Values.secretsgeneric.tlsCert | b64enc | quote }}
{{- end }}
