{{- if .Values.rbac.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ template "serviceaccount-psp.name" . }}-psp-use-pod-security-policy-role"
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ["use"]
  resourceNames:
    - "{{ template "serviceaccount-psp.name" . }}-psp-pod-running-policy"
{{- end }}
