# Default values for datarepo-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: gcr.io
  repository: broad-jade-dev/jade-data-repo
  tag: 8e65464
  pullPolicy: IfNotPresent
  port: 8080

env: # environment variables
  serverContextpath:
  serverPort:
  springDatasourceTomcatTestOnBorrow:
  springDatasourceTomcatValidationQuery:
  springJacksonSerializationWriteDatesAsTimestamps:
  springLiquibaseEnabled:
  springProfilesActive:
  springfoxDocumentationSwaggerV2Path:
  dbMigrateDropallonstart:
  dbMigrateUpdateallonstart:
  dbDatarepoUri:
  dbDatarepoUsername:
  dbDatarepoPassword:
  dbDatarepoChangesetfile:
  dbStairwayUri:
  dbStairwayUsername:
  dbStairwayPassword:
  dbStairwayChangesetfile:
  dbStairwayForceclean:
  oauthClientid:
  oauthSchemename:
  oauthLoginendpoint:
  oauthScopes:
  datarepoResourceid:
  datarepoUseremail:
  datarepoDnsname:
  datarepoUserid:
  datarepoMaxstairwaythreads:
  datarepoGcsBucket:
  datarepoGcsRegion:
  datarepoGcsConnecttimeoutseconds:
  datarepoGcsReadtimeoutseconds:
  samBasepath:
  samStewardsgroupemail:
  samRetryinitialwaitseconds:
  samRetrymaximumwaitseconds:
  samOperationtimeoutseconds:
  googleProjectid:
  googleApplicationname:
  googleProjectcreatetimeoutseconds:
  googleCorebillingaccount:
  googleParentresourcetype:
  googleParentresourceid:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

rbac:
  # Specifies whether a psp should be created
  create: false

service:
  port: 8080
  type: ClusterIP

## create new secrets
secretsgeneric:
  datarepoPassword:
  stairwayPassword:
  serivceAccountCredentialFileJson:

## Specify an existing secret holding the cloud-sql database credentials
existingSecretDB: ""
## The key in the existing secret that stores the Datarepo DB credentials
existingDatarepoDbSecretKey: ""
## The key in the existing secret that stores the stairway DB credentials
existingStairwayDbSecretKey: ""

## Specify an existing secret holding the cloud-sql service account credentials
existingSecretSA: ""
## The key in the existing secret that stores the GCP Service account credentials
existingServiceAccountSecretKey: ""
