# Default values for datarepo-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/broad-jade-dev/jade-data-repo
  version: latest
  pullPolicy: IfNotPresent
  port: 8080

env: # environment variables
  serverContextpath:
  serverPort:
  springDatasourceTomcatTestOnBorrow:
  springDatasourceTomcatValidationQuery:
  springJacksonSerializationWriteDatesAsTimestamps:
  springLiquibaseEnabled:
  springProfilesActive:
  springfoxDocumentationSwaggerV2Path:
  dbMigrateDropallonstart:
  dbMigrateUpdateallonstart:
  dbDatarepoUri:
  dbDatarepoUsername:
  dbDatarepoPassword:
  dbDatarepoChangesetfile:
  dbStairwayUri:
  dbStairwayUsername:
  dbStairwayPassword:
  dbStairwayChangesetfile:
  dbStairwayForceclean:
  oauthClientid:
  oauthSchemename:
  oauthLoginendpoint:
  oauthScopes:
  datarepoResourceid:
  datarepoUseremail:
  datarepoDnsname:
  datarepoUserid:
  datarepoMaxstairwaythreads:
  datarepoGcsBucket:
  datarepoGcsRegion:
  datarepoGcsConnecttimeoutseconds:
  datarepoGcsReadtimeoutseconds:
  samBasepath:
  samStewardsgroupemail:
  samRetryinitialwaitseconds:
  samRetrymaximumwaitseconds:
  samOperationtimeoutseconds:
  googleProjectid:
  googleApplicationname:
  googleProjectcreatetimeoutseconds:
  googleCorebillingaccount:
  googleParentresourcetype:
  googleParentresourceid:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

rbac:
  # Specifies whether a psp should be created
  create: false

service:
  port: 8080
  type: ClusterIP

secretsgeneric:
  existingSecret: true
  datarepoPassword:
  stairwayPassword:
  credentialFileJson:

secretsvault:
  existingSecret: false
  datarepoPassword:
  stairwayPassword:
  credentialFileJson:
