name: Release Indivdual Charts

on:
  push:
    branches:
      - master
    paths:
      - '!charts/datarepo/**'
      - '!.github/**'
      - '!README.md'


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: add repo
        run: |
          helm repo add datarepo-helm https://broadinstitute.github.io/datarepo-helm
          helm repo add stable https://charts.helm.sh/stable
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
