name: Integration Chart Promotion
env:
  charts: gcloud-sqlproxy datarepo-api datarepo-ui oidc-proxy

on:
  workflow_dispatch: {}

jobs:
  indivdual_chart_promotion:
    strategy:
      matrix:
        include:
          - app: datarepo-api
            repo: "jade-data-repo"
            filename: "int-and-connected-test-run.yml"
            jobname: "deploy_test_integration"
          - app: datarepo-ui
            repo: "jade-data-repo-ui"
            filename: "test-e2e.yml"
            jobname: "e2e_test"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Checkout ${{ matrix.repo }} repo'
        uses: actions/checkout@v2
        with:
          repository: 'databiosphere/${{ matrix.repo }}'
          token: ${{ secrets.CR_TOKEN }}
          path: ${{ matrix.repo }}
          persist-credentials: false

      - name: "Find latest version chart version"
        id: chartversion
        run: |
          for i in $(echo ${{ env.charts }})
          do
            echo "::set-output name=$i-version::$(docker run --rm -v ${PWD}:/workdir mikefarah/yq yq read charts/$i/Chart.yaml version)"
          done

      - name: "Find and replace datarepo-api chartVersion version in integration action"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i ${{ matrix.repo }}/.github/workflows/${{ matrix.filename }} "jobs.${{ matrix.jobname }}.steps.(name==Deploy to cluster with Helm).with.helm_datarepo_api_chart_version" ${{ steps.chartversion.outputs.datarepo-api-version }}

      - name: "Find and replace datarepo-ui chartVersion version in integration action"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i ${{ matrix.repo }}/.github/workflows/${{ matrix.filename }} "jobs.${{ matrix.jobname }}.steps.(name==Deploy to cluster with Helm).with.helm_datarepo_ui_chart_version" ${{ steps.chartversion.outputs.datarepo-ui-version }}

      - name: "Find and replace gcloud-sqlproxy chartVersion version in integration action"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i ${{ matrix.repo }}/.github/workflows/${{ matrix.filename }} "jobs.${{ matrix.jobname }}.steps.(name==Deploy to cluster with Helm).with.helm_gcloud_sqlproxy_chart_version" ${{ steps.chartversion.outputs.gcloud-sqlproxy-version }}

      - name: "Find and replace oidc-proxy chartVersion version in integration action"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i ${{ matrix.repo }}/.github/workflows/${{ matrix.filename }} "jobs.${{ matrix.jobname }}.steps.(name==Deploy to cluster with Helm).with.helm_oidc_proxy_chart_version" ${{ steps.chartversion.outputs.oidc-proxy-version }}

      - name: print new chart
        uses: docker://mikefarah/yq:3
        with:
          args: yq r ${{ matrix.repo }}/.github/workflows/${{ matrix.filename }}

      - name: Create pull request
        uses: broadinstitute/create-pull-request@v3.5.0  #forked from peter-evans/create-pull-request
        id: create-pr
        with:
          token: ${{ secrets.CR_TOKEN }}
          path: ${{ matrix.repo }}
          commit-message: "Datarepo Integration mutli chart version update"
          committer: datarepo-bot <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "Datarepo helm integraton chart version update"
          branch: "version-update/int-version-update-${{ env.GITHUB_RUN_ID }}"
          body: |
            gcloud-sqlproxy-version: ${{ steps.chartversion.outputs.gcloud-sqlproxy-version }}
            datarpeo-api-version: ${{ steps.chartversion.outputs.datarepo-api-version }}
            datarpeo-ui-version: ${{ steps.chartversion.outputs.datarepo-ui-version }}
            oidc-proxy-version: ${{ steps.chartversion.outputs.oidc-proxy-version }}
            *Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).*
          labels: "helm,datarepo,version-update,automerge"
