name: Create chart Datarepo chart

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - '!charts/**'
      - '!.github/**'
      - '!README.md'
      - 'charts/datarepo-api/**'
      - 'charts/datarepo-ui/**'
      - 'charts/create-secret-manager-secret/**'
      - 'charts/gcloud-sqlproxy/**'
      - 'charts/oidc-proxy/**'
      - 'charts/gcp-managed-cert/**'

jobs:
  release_new_umbrella_dr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0   # otherwise, you will failed to push refs to dest repo
          token: "${{ secrets.BROADBOT_TOKEN }}" #otherwise merge will fail
          ref: master

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: add repo
        run: |
          helm repo add datarepo-helm https://broadinstitute.github.io/datarepo-helm
          helm repo add stable https://charts.helm.sh/stable
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"

      - name: "Create new umbrealla chart"
        uses: broadinstitute/datarepo-umbrella-release-action@0.2.0

      - name: "Merge using new merge action"
        uses: broadinstitute/datarepo-actions/actions/merger@0.38.0
        env:
          COMMIT_MESSAGE: "Datarepo umbrella chart update"
          GITHUB_REPO: datarepo-helm
          MERGE_BRANCH: master

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
