name: Release chart non dr chart

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - '!.github/**'
      - '!README.md'
      - '!charts/datarepo-api/**'
      - '!charts/datarepo-ui/**'
      - '!charts/create-secret-manager-secret/**'
      - '!charts/gcloud-sqlproxy/**'
      - '!charts/oidc-proxy/**'
      - 'charts/**'

jobs:
  release_non_dr_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0   # otherwise, you will failed to push refs to dest repo
          token: "${{ secrets.CR_TOKEN }}"

      - name: Trigger action to run chart-releaser
        uses: broadinstitute/workflow-dispatch@v1
        with:
          workflow: Release helm charts
          token: ${{ secrets.WORKFLOW_DISPATCH }}
