name: Release chart Datarepo chart

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - '!charts/**'
      - '!.github/**'
      - '!README.md'
      - 'charts/datarepo/**'

jobs:
  release_new_umbrella_dr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.BROADBOT_TOKEN }}
          fetch-depth: 0   # otherwise, you will failed to push refs to dest repo
  release_umbrella_helm_charts:
    needs: release_new_umbrella_dr
    uses: ./.github/workflows/chart-releaser.yaml
    secrets: inherit
  alpha_chart_promotion:
    needs: release_new_umbrella_dr
    uses: ./.github/workflows/terraAlphaChartBump.yaml
    secrets: inherit
  integration_chart_promotion:
    needs: release_new_umbrella_dr
    uses: ./.github/workflows/integrationChartBump.yaml
    secrets: inherit
  notify_slack:
    needs:
      - release_new_umbrella_dr
      - release_umbrella_helm_charts
      - alpha_chart_promotion
      - integration_chart_promotion
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: "Notify Slack"
        if: always()
        uses: broadinstitute/action-slack@v3.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }} # required to work with job field
        with:
          status: ${{ job.status }}
          fields: job,repo,message
          channel: "#jade-spam"
          username: "datarepo-helm actions"
          text: "Release Datarepo Chart"
