name: Create chart Datarepo chart

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - '!charts/**'
      - '!.github/**'
      - '!README.md'
      - 'charts/datarepo-api/**'
      - 'charts/datarepo-ui/**'
      - 'charts/create-secret-manager-secret/**'
      - 'charts/gcloud-sqlproxy/**'
      - 'charts/oidc-proxy/**'
      - 'charts/gcp-managed-cert/**'

jobs:
  release_new_umbrella_dr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0   # otherwise, you will failed to push refs to dest repo
          token: "${{ secrets.CR_TOKEN }}"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: add repo
        run: |
          helm repo add datarepo-helm https://broadinstitute.github.io/datarepo-helm
          helm repo add stable https://charts.helm.sh/stable
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"

      - name: "Create new umbrealla chart"
        uses: broadinstitute/datarepo-umbrella-release-action@0.2.0

      - name: Create pull request
        uses: broadinstitute/create-pull-request@v3.5.0  #forked from peter-evans/create-pull-request
        id: create-pr
        with:
          token: ${{ secrets.CR_TOKEN }}
          commit-message: "Datarepo umbrella chart update"
          committer: datarepo-bot <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "Datarepo umbrella version update"
          branch: "version-update/datarepo-version-update-${{ github.run_id }}"
          body: |
            *Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).*
          labels: "helm,datarepo,version-update,automerge"

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
