name: Release umbrella chart

on:
  push:
    branches:
      - master
    paths:
      - 'charts/datarepo-api/**'
      - 'charts/datarepo-ui/**'
      - 'charts/create-secret-manager-secret/**'
      - 'charts/gcloud-sqlproxy/**'
      - 'charts/oidc-proxy/**'

jobs:
  release_new_umbrella:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: "Create new umbrealla chart"
        uses: broadinstitute/datarepo-umbrella-release-action@ms-debug

      - name: Commit files
        run: |
          git config --local user.email "robot@jade.team"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
          git diff

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
