name: Release chart Datarepo chart

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - '!charts/**'
      - '!.github/**'
      - '!README.md'
      - 'charts/datarepo-api/**'
      - 'charts/datarepo-ui/**'
      - 'charts/create-secret-manager-secret/**'
      - 'charts/gcloud-sqlproxy/**'
      - 'charts/oidc-proxy/**'
      - 'charts/gcp-managed-cert/**'

jobs:
  release_new_umbrella_dr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0   # otherwise, you will failed to push refs to dest repo
          token: "${{ secrets.CR_TOKEN }}"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: add repo
        run: |
          helm repo add datarepo-helm https://broadinstitute.github.io/datarepo-helm
          helm repo add stable https://charts.helm.sh/stable
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"

      - name: "Create new umbrealla chart"
        uses: broadinstitute/datarepo-umbrella-release-action@0.2.0

      - name: Commit files
        run: |
          git config --local user.email "robot@jade.team"
          git config --local user.name "GitHub Action"
          git commit -m "Added changes datarepo charts" -a
          git diff
          git push
          sleep 5

      - name: Trigger action to run chart-releaser for  datarepo umbrella
        uses: broadinstitute/workflow-dispatch@v1
        with:
          workflow: Release helm charts
          token: ${{ secrets.WORKFLOW_DISPATCH }}
