name: Release chart Datarepo chart

on:
  push:
    branches:
      - master
    paths:
      - '!charts/**'
      - '!.github/**'
      - '!README.md'
      - 'charts/datarepo/**'

jobs:
  release_new_umbrella_dr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          token: ${{ secrets.CR_TOKEN }}
          fetch-depth: 0   # otherwise, you will failed to push refs to dest repo

      - name: Trigger action to run chart-releaser for  datarepo umbrella
        if: github.event.pull_request.merged == true
        uses: broadinstitute/workflow-dispatch@v1.1
        with:
          workflow: Release helm charts
          token: ${{ secrets.WORKFLOW_DISPATCH }}

      - name: Trigger action to run alpha chart promotion
        uses: broadinstitute/workflow-dispatch@v1.1
        with:
          workflow: Alpha Chart Promotion
          token: ${{ secrets.WORKFLOW_DISPATCH }}

      - name: Trigger action to run alpha chart promotion
        uses: broadinstitute/workflow-dispatch@v1.1
        with:
          workflow: Integration Chart Promotion
          token: ${{ secrets.WORKFLOW_DISPATCH }}
