name: Release chart non dr chart

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - 'charts/**'
      - '!.github/**'
      - '!README.md'
      - '!charts/datarepo-api/**'
      - '!charts/datarepo/**'
      - '!charts/datarepo-ui/**'
      - '!charts/create-secret-manager-secret/**'
      - '!charts/gcloud-sqlproxy/**'
      - '!charts/oidc-proxy/**'
      - '!charts/de-elasticsearch/**'

jobs:
  release_non_dr_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0   # otherwise, you will failed to push refs to dest repo
          token: "${{ secrets.CR_TOKEN }}"

      - name: Trigger action to run chart-releaser
        uses: broadinstitute/workflow-dispatch@v1
        with:
          workflow: Release helm charts
          token: ${{ secrets.BROADBOT_TOKEN }}

      - name: "Notify Slack"
        if: always()
        uses: broadinstitute/action-slack@v3.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }} # required to work with job field
        with:
          status: ${{ job.status }}
          fields: job,repo,message
          channel: "#jade-spam"
          username: "datarepo-helm actions"
          text: "Release Non-Datarepo Charts"
