name: Release chart non dr chart

on:
  push:
    branches:
      - master
    paths:
      - '!.github/**'
      - '!charts/datarepo-api/**'
      - '!charts/datarepo-ui/**'
      - '!charts/create-secret-manager-secret/**'
      - '!charts/gcloud-sqlproxy/**'
      - '!charts/oidc-proxy/**'
      - 'charts/**'

jobs:
  release_non_dr_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0   # otherwise, you will failed to push refs to dest repo
          token: "${{ secrets.CR_TOKEN }}"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"

      - name: Commit files
        run: |
          git config --local user.email "robot@jade.team"
          git config --local user.name "GitHub Action"
          git commit -m "Added changes to non datarepo charts" -a
          git diff
          git push
