name: Release chart non dr chart

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - 'charts/**'
      - '!.github/**'
      - '!README.md'
      - '!charts/datarepo-api/**'
      - '!charts/datarepo/**'
      - '!charts/datarepo-ui/**'
      - '!charts/create-secret-manager-secret/**'
      - '!charts/gcloud-sqlproxy/**'
      - '!charts/oidc-proxy/**'

jobs:
  release_non_dr_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0   # otherwise, you will failed to push refs to dest repo
          token: "${{ secrets.BROADBOT_TOKEN }}"
  release_helm_charts:
    needs: release_non_dr_chart
    uses: ./.github/workflows/chart-releaser.yaml
    secrets: inherit

  notify_slack:
    needs:
      - release_non_dr_chart
      - release_helm_charts
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: "Notify Slack"
        uses: broadinstitute/action-slack@v3.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }} # required to work with job field
        with:
          status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
          fields: job,repo,message
          channel: "#jade-spam"
          username: "datarepo-helm actions"
          text: "Release Non-Datarepo Charts"
