name: Release chart Datarepo chart

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - '!charts/**'
      - '!.github/**'
      - '!README.md'
      - 'charts/datarepo/**'

jobs:
  release_new_umbrella_dr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.BROADBOT_TOKEN }}
          fetch-depth: 0   # otherwise, you will failed to push refs to dest repo
  release_umbrella_helm_charts:
    needs: release_new_umbrella_dr
    uses: ./.github/workflows/chart-releaser.yaml
    secrets: inherit
  report-workflow:
    uses: broadinstitute/sherlock/.github/workflows/client-report-workflow.yaml@main
    with:
      relates-to-chart-releases: 'datarepo-dev'
      notify-slack-channels-upon-workflow-failure: ${{ vars.SLACK_NOTIFICATION_CHANNELS }}
      notify-slack-channels-upon-workflow-retry: ${{ vars.SLACK_NOTIFICATION_CHANNELS }}
    permissions:
      id-token: write
