
name: Alpha Chart Promotion
on:
  workflow_dispatch: {}

jobs:
  alpha_chart_promotion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Checkout jade-data-repo repo'
        uses: actions/checkout@v2
        with:
          repository: 'databiosphere/jade-data-repo'
          token: ${{ secrets.BROADBOT_TOKEN }}
          path: jade-data-repo

      - name: "Find latest version of Datarepo chart version in datarepo/Chart.yaml"
        id: chartversion
        run: |
          echo "::set-output name=version::$(docker run --rm -v ${PWD}:/workdir mikefarah/yq:3 yq read charts/datarepo/Chart.yaml version)"

      - name: "Find and replace Datarepo chartVersion version in alpha action"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i jade-data-repo/.github/workflows/alpha-promotion.yaml env.chartVersion ${{ steps.chartversion.outputs.version }}

      - name: "Merge changes to jade-data-repo"
        env:
          GITHUB_EMAIL: "broadbot@broadinstitute.org"
          GITHUB_USERNAME: "broadbot"
          COMMIT_MESSAGE: "Datarepo chart version update: ${{ steps.chartversion.outputs.version }}"
          MODIFIED_REPO: jade-data-repo
          MODIFIED_FILEPATH: .github/workflows/alpha-promotion.yaml
          DESTINATION_BRANCH: develop
        run: |
          #TODO: pull this into datarepo-actions repo
          echo "[INFO] git config email to $GITHUB_EMAIL"
          git config --global user.email "$GITHUB_EMAIL"
          echo "[INFO] git config name $GITHUB_USERNAME"
          git config --global user.name "$GITHUB_USERNAME"
          echo "[INFO] git add file $MODIFIED_FILEPATH"
          git add $MODIFIED_FILEPATH
          echo "[INFO] commit w/ msg: $COMMIT_MESSAGE"
          git commit -m $COMMIT_MESSAGE"
          echo "[INFO] git push $DESTINATION_BRANCH"
          git push origin $DESTINATION_BRANCH
          echo "[INFO] post push"
          commit=$(git rev-parse HEAD)
          echo "[INFO] commit: $commit"
