
name: Alpha Chart Promotion
on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  alpha_chart_promotion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: datarepo-helm

      - name: 'Checkout jade-data-repo repo'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'databiosphere/jade-data-repo'
          token: ${{ secrets.BROADBOT_TOKEN }}
          path: jade-data-repo

      - name: "Find latest version of Datarepo chart version in datarepo/Chart.yaml"
        id: chartversion
        run: |
          echo "::set-output name=version::$(docker run --rm -v ${PWD}:/workdir mikefarah/yq:3 yq read datarepo-helm/charts/datarepo/Chart.yaml version)"

      # - name: "Find and replace Datarepo chartVersion version in alpha action"
      #   uses: docker://mikefarah/yq:3
      #   with:
      #     args: yq w -i jade-data-repo/.github/workflows/alpha-promotion.yaml env.chartVersion ${{ steps.chartversion.outputs.version }}

      # - name: "[jade-data-repo] Merge Changes"
      #   uses: broadinstitute/datarepo-actions/actions/merger@0.66.0
      #   env:
      #     COMMIT_MESSAGE: "Datarepo chart version update: ${{ steps.chartversion.outputs.version }}"
      #     SWITCH_DIRECTORIES: "true"

      - name: "Notify Slack"
        if: ${{ github.event_name != 'workflow_call' && always() }} # workflow_call has own slack notification
        uses: broadinstitute/action-slack@v3.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }} # required to work with job field
        with:
          status: ${{ job.status }}
          fields: job,repo,message
          channel: "#jade-spam"
          username: "datarepo-helm actions"
          text: "Alpha Chart Promotion"
