
name: Alpha Chart Promotion
on:
  dispatch: {}
  pull_request:
    branches:
      - master

jobs:
  alpha_chart_promotion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Checkout jade-data-repo repo'
        uses: actions/checkout@v2
        with:
          repository: 'databiosphere/jade-data-repo'
          token: ${{ secrets.CR_TOKEN }}
          path: terra-helmfile
          persist-credentials: false

      - name: "Find latest version of Datarepo chart version in datarepo/Chart.yaml"
        id: chartversion
        uses: docker://mikefarah/yq:latest
        with:
          args: yq read charts/datarepo/Chart.yaml version

      - name: "echo outputs"
        run: |
          echo ${{ steps.chartversion.output }}

#      - name: "Find and replace Datarepo chartVersion version in alpha action"
#        uses: docker://mikefarah/yq:latest
#        with:
#          args: yq w -i jade-data-repo/.github/workflows/alpha-promotion.yaml version ${{ steps.chartversion }}

#      - name: Create pull request
#        id: create-pr
#        with:
#          token: ${{ secrets.TERRA_HELMFILE_TOKEN }}
#          path: terra-helmfile
#          commit-message: "Datarepo version update: ${{ steps.apiprevioustag.outputs.tag }}"
#          committer: datarepo-bot <noreply@github.com>
#          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
#          title: "Datarepo version update: ${{ steps.apiprevioustag.outputs.tag }}"
#          branch: "version-update/${{ steps.apiprevioustag.outputs.tag }}"
#          body: |
#            Update versions in **${{ steps.apiprevioustag.outputs.tag }}**.
#            *Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).*
#          labels: "broadbot,datarepo,automerge,version-update"
