
name: Alpha Chart Promotion
on:
  workflow_dispatch: {}

jobs:
  alpha_chart_promotion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: datarepo-helm

      - name: "Find latest version of Datarepo chart version in datarepo/Chart.yaml"
        id: chartversion
        run: |
          echo "::set-output name=version::$(docker run --rm -v ${PWD}:/workdir mikefarah/yq:3 yq read datarepo-helm/charts/datarepo/Chart.yaml version)"

      - name: "merge"
        uses: actions/checkout@v2
        with:
          repository: 'databiosphere/jade-data-repo'
          token: ${{ secrets.BROADBOT_TOKEN }}
          path: jade-data-repo
        run: |
          docker run --rm -v ${PWD}:/workdir mikefarah/yq:3 yq w -i jade-data-repo/.github/workflows/alpha-promotion.yaml  env.chartVersion ${{ steps.chartversion.outputs.version }}
          git config user.name broadbot
          git config user.email broadbot@broadinstitute.org
          git add .
          git commit -m "Datarepo chart version update: ${{ steps.chartversion.outputs.version }}"
          git push origin develop
